/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_JniBridge */

#ifndef _Included_io_github_lizhangqu_JniBridge
#define _Included_io_github_lizhangqu_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_lizhangqu_JniBridge
 * Method:    nativeCalculateSquares
 * Signature: ([J)[J
 */
JNIEXPORT jlongArray JNICALL Java_io_github_lizhangqu_JniBridge_nativeCalculateSquares
  (JNIEnv *env, jobject obj, jlongArray values, jint numValues);

/*
 * Class:     io_github_lizhangqu_JniBridge
 * Method:    version
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_io_github_lizhangqu_JniBridge_version
    (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif